### ISSUE TITLE
PinView.java line 339

### ISSUE THREAD

**Issue by brodjag** [ChaosLeung/PinView#76]
#Bug report.
Crash:

Fatal Exception: java.lang.IndexOutOfBoundsException: offset(6) should be less than line limit(0)
       at android.text.TextLine.measure(TextLine.java:389)
       at android.text.Layout.getHorizontal(Layout.java:1254)
       at android.text.Layout.getHorizontal(Layout.java:1230)
       at android.text.Layout.getPrimaryHorizontal(Layout.java:1200)
       at android.text.Layout.getPrimaryHorizontal(Layout.java:1189)
       at android.widget.Editor$TextActionModeCallback.onGetContentRect(Editor.java:5434)
       at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onGetContentRect(DecorView.java:5762)
       at com.android.internal.view.FloatingActionMode.invalidateContentRect(FloatingActionMode.java:161)
       at android.widget.Editor.refreshTextActionMode(Editor.java:2628)
       at android.widget.TextView.spanChange(TextView.java:12091)
       at android.widget.TextView$ChangeWatcher.onSpanChanged(TextView.java:15295)
       at android.text.SpannableStringBuilder.sendSpanChanged(SpannableStringBuilder.java:1321)
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:766)
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:690)
       at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java:140)
       at android.text.Selection.setSelection(Selection.java:96)
       at android.text.Selection.setSelection(Selection.java:78)
       at android.text.Selection.setSelection(Selection.java:153)
       at android.widget.EditText.setSelection(EditText.java:147)
       at com.chaos.view.PinView.moveSelectionToEnd(PinView.java:339)
       at com.chaos.view.PinView.onSelectionChanged(PinView.java:334)
       at android.widget.TextView.spanChange(TextView.java:12098)
       at android.widget.TextView$ChangeWatcher.onSpanAdded(TextView.java:15302)
       at android.text.SpannableStringBuilder.sendSpanAdded(SpannableStringBuilder.java:1301)
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:791)
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:690)
       at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java:140)
       at android.text.Selection.setSelection(Selection.java:96)
       at android.text.Selection.setSelection(Selection.java:78)
       at android.text.Selection.setSelection(Selection.java:153)
       at com.chaos.view.DefaultMovementMethod.initialize(DefaultMovementMethod.java:50)
       at android.widget.TextView.setText(TextView.java:6936)
       at android.widget.TextView.setText(TextView.java:6751)
       at android.widget.EditText.setText(EditText.java:133)
       at android.widget.TextView.setText(TextView.java:6703)
       at u24_.co.uk.u24_2018.bindingAdapters.PinViewAdapterClipboard.pastClipboard(PinViewAdapterClipboard.java:30)
       at u24_.co.uk.u24_2018.databinding.ResetVerificationCodeStepBindingImpl._internalCallbackOnLongClick(ResetVerificationCodeStepBindingImpl.java:182)
       at u24_.co.uk.u24_2018.generated.callback.OnLongClickListener.onLongClick(OnLongClickListener.java:11)
       at android.view.View.performLongClickInternal(View.java:7961)
       at android.view.View.performLongClick(View.java:7919)
       at android.widget.TextView.performLongClick(TextView.java:14046)
       at android.view.View.performLongClick(View.java:7937)
       at android.view.View$CheckForLongPress.run(View.java:30821)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8741)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

##### Info:

 * PinView version: 1.4.4
 * Device OS version:  android 11
 * Device Name:  samsung Galaxy s21 5G and Galaxy A32

##### Reproduction Steps:
 it rarely occurs. Couldn't replicate on my device.
 only in firebase crashlitics

##### What did I do:
User pasts text from clipboard.
pinView.setText(str);

**Comment by Mohyddine** [comment]
Same issue
PinView version: 1.4.4
Device OS version: Android 13
Device Name: Samsung Galaxy A52 5G and Galaxy A52s 5G
it rarely occurs. Couldn't replicate it on my device.
only in firebase Crashlytics

**Comment by radhey-telcoin** [comment]
Any update on this? Happens to me as well.

**Comment by iLona-Karpova** [comment]
Based on the stack trace and the code provided, here is an analysis of why this crash is happening.

### What is causing the crash?

1. **Autofill Trigger:** The crash is initiated by the Android Autofill framework (`AutofillManager.autofill`). When autofill runs, it calls `setText()` on your `PinView` to populate the PIN/OTP.
2. **Synchronous Selection Change:** Inside `TextView.setText()`, the framework initializes the movement method, which indirectly triggers a selection change and calls your overridden `onSelectionChanged()` method. 
3. **Cursor Manipulation before Layout is Ready:** In `PinView`, your `onSelectionChanged()` method forces the cursor to the end of the text synchronously by calling `moveSelectionToEnd() -> setSelection(this.length)`.
4. **Samsung's Custom Framework Behavior:** On Samsung devices, changing the selection while an Autofill/Clipboard popup is active triggers the text editor to refresh the floating action mode (`Editor.refreshTextActionMode`). To position this popup correctly, the system calculates the content rectangle by measuring the text (`TextLine.measure`).
5. **The Crash:** Because `setText()` has not actually finished running yet, the `TextView`'s internal text `Layout` has not been recalculated. The layout still thinks the line length is `0`, but you just moved the cursor offset to the end of the newly pasted text (e.g., offset `6`). The system tries to measure the bounds for offset `6` on a layout with limit `0`, resulting in the `IndexOutOfBoundsException: offset(6) should be less than line limit(0)`.

### How to fix it

To resolve this issue, you should avoid modifying the selection synchronously while the `TextView` is potentially still in the middle of a text update or layout pass. 

You can fix this by deferring the cursor movement to the next message queue loop using `View.post()`.

Modify your `moveSelectionToEnd()` function in `PinView.kt` like this:

```kotlin
// ... existing code ...
      override fun onSelectionChanged(selStart: Int, selEnd: Int) {
        super.onSelectionChanged(selStart, selEnd)
        text?.run {
          if (selEnd != this.length) {
            moveSelectionToEnd()
          }
        }
      }

      private fun moveSelectionToEnd() {
        post {
          text?.run {
            setSelection(this.length)
          }
        }
      }

      override fun drawableStateChanged() {
// ... existing code ...
```


By wrapping the `setSelection` call in `post { }`, you ensure that the selection update happens *after* `setText()` has completely finished and the layout has been correctly measured and updated by the Android UI thread.

Powered by Gemini 3
